name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install dotnet-sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner
      
    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage
        
    - name: Test
      run: dotnet test --configuration Release --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Sonar Cloud Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      run: |
        dotnet sonarscanner begin /k:${{ secrets.SONAR_PROJECT_KEY }} d:sonar.token=${{ secrets.SONAR_TOKEN }} d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
        dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}