name: Snyk Scanning
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
    security:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Setup .NET
          uses: actions/setup-dotnet@3.0.3
        - name: Restore dependencies
          run: dotnet restore
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/dotnet@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}